# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sudoku_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 638)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cell11 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell11.setGeometry(QtCore.QRect(10, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell11.setFont(font)
        self.cell11.setObjectName("cell11")
        self.cell12 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell12.setGeometry(QtCore.QRect(70, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell12.setFont(font)
        self.cell12.setObjectName("cell12")
        self.cell13 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell13.setGeometry(QtCore.QRect(130, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell13.setFont(font)
        self.cell13.setObjectName("cell13")
        self.cell14 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell14.setGeometry(QtCore.QRect(190, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell14.setFont(font)
        self.cell14.setObjectName("cell14")
        self.cell16 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell16.setGeometry(QtCore.QRect(310, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell16.setFont(font)
        self.cell16.setObjectName("cell16")
        self.cell15 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell15.setGeometry(QtCore.QRect(250, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell15.setFont(font)
        self.cell15.setObjectName("cell15")
        self.cell17 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell17.setGeometry(QtCore.QRect(370, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell17.setFont(font)
        self.cell17.setObjectName("cell17")
        self.cell18 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell18.setGeometry(QtCore.QRect(430, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell18.setFont(font)
        self.cell18.setObjectName("cell18")
        self.cell19 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell19.setGeometry(QtCore.QRect(490, 50, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell19.setFont(font)
        self.cell19.setObjectName("cell19")
        self.cell24 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell24.setGeometry(QtCore.QRect(190, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell24.setFont(font)
        self.cell24.setObjectName("cell24")
        self.cell28 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell28.setGeometry(QtCore.QRect(430, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell28.setFont(font)
        self.cell28.setObjectName("cell28")
        self.cell27 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell27.setGeometry(QtCore.QRect(370, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell27.setFont(font)
        self.cell27.setObjectName("cell27")
        self.cell21 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell21.setGeometry(QtCore.QRect(10, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell21.setFont(font)
        self.cell21.setObjectName("cell21")
        self.cell25 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell25.setGeometry(QtCore.QRect(250, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell25.setFont(font)
        self.cell25.setObjectName("cell25")
        self.cell23 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell23.setGeometry(QtCore.QRect(130, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell23.setFont(font)
        self.cell23.setObjectName("cell23")
        self.cell26 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell26.setGeometry(QtCore.QRect(310, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell26.setFont(font)
        self.cell26.setObjectName("cell26")
        self.cell22 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell22.setGeometry(QtCore.QRect(70, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell22.setFont(font)
        self.cell22.setObjectName("cell22")
        self.cell29 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell29.setGeometry(QtCore.QRect(490, 110, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell29.setFont(font)
        self.cell29.setObjectName("cell29")
        self.cell94 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell94.setGeometry(QtCore.QRect(190, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell94.setFont(font)
        self.cell94.setObjectName("cell94")
        self.cell98 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell98.setGeometry(QtCore.QRect(430, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell98.setFont(font)
        self.cell98.setObjectName("cell98")
        self.cell97 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell97.setGeometry(QtCore.QRect(370, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell97.setFont(font)
        self.cell97.setObjectName("cell97")
        self.cell91 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell91.setGeometry(QtCore.QRect(10, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell91.setFont(font)
        self.cell91.setObjectName("cell91")
        self.cell95 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell95.setGeometry(QtCore.QRect(250, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell95.setFont(font)
        self.cell95.setObjectName("cell95")
        self.cell93 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell93.setGeometry(QtCore.QRect(130, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell93.setFont(font)
        self.cell93.setObjectName("cell93")
        self.cell96 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell96.setGeometry(QtCore.QRect(310, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell96.setFont(font)
        self.cell96.setObjectName("cell96")
        self.cell92 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell92.setGeometry(QtCore.QRect(70, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell92.setFont(font)
        self.cell92.setObjectName("cell92")
        self.cell99 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell99.setGeometry(QtCore.QRect(490, 530, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell99.setFont(font)
        self.cell99.setObjectName("cell99")
        self.cell84 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell84.setGeometry(QtCore.QRect(190, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell84.setFont(font)
        self.cell84.setObjectName("cell84")
        self.cell88 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell88.setGeometry(QtCore.QRect(430, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell88.setFont(font)
        self.cell88.setObjectName("cell88")
        self.cell87 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell87.setGeometry(QtCore.QRect(370, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell87.setFont(font)
        self.cell87.setObjectName("cell87")
        self.cell81 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell81.setGeometry(QtCore.QRect(10, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell81.setFont(font)
        self.cell81.setObjectName("cell81")
        self.cell85 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell85.setGeometry(QtCore.QRect(250, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell85.setFont(font)
        self.cell85.setObjectName("cell85")
        self.cell83 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell83.setGeometry(QtCore.QRect(130, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell83.setFont(font)
        self.cell83.setObjectName("cell83")
        self.cell86 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell86.setGeometry(QtCore.QRect(310, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell86.setFont(font)
        self.cell86.setObjectName("cell86")
        self.cell82 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell82.setGeometry(QtCore.QRect(70, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell82.setFont(font)
        self.cell82.setObjectName("cell82")
        self.cell89 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell89.setGeometry(QtCore.QRect(490, 470, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell89.setFont(font)
        self.cell89.setObjectName("cell89")
        self.cell74 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell74.setGeometry(QtCore.QRect(190, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell74.setFont(font)
        self.cell74.setObjectName("cell74")
        self.cell78 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell78.setGeometry(QtCore.QRect(430, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell78.setFont(font)
        self.cell78.setObjectName("cell78")
        self.cell77 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell77.setGeometry(QtCore.QRect(370, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell77.setFont(font)
        self.cell77.setObjectName("cell77")
        self.cell71 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell71.setGeometry(QtCore.QRect(10, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell71.setFont(font)
        self.cell71.setObjectName("cell71")
        self.cell75 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell75.setGeometry(QtCore.QRect(250, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell75.setFont(font)
        self.cell75.setObjectName("cell75")
        self.cell73 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell73.setGeometry(QtCore.QRect(130, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell73.setFont(font)
        self.cell73.setObjectName("cell73")
        self.cell76 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell76.setGeometry(QtCore.QRect(310, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell76.setFont(font)
        self.cell76.setObjectName("cell76")
        self.cell72 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell72.setGeometry(QtCore.QRect(70, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell72.setFont(font)
        self.cell72.setObjectName("cell72")
        self.cell79 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell79.setGeometry(QtCore.QRect(490, 410, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell79.setFont(font)
        self.cell79.setObjectName("cell79")
        self.cell64 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell64.setGeometry(QtCore.QRect(190, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell64.setFont(font)
        self.cell64.setObjectName("cell64")
        self.cell68 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell68.setGeometry(QtCore.QRect(430, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell68.setFont(font)
        self.cell68.setObjectName("cell68")
        self.cell67 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell67.setGeometry(QtCore.QRect(370, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell67.setFont(font)
        self.cell67.setObjectName("cell67")
        self.cell61 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell61.setGeometry(QtCore.QRect(10, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell61.setFont(font)
        self.cell61.setObjectName("cell61")
        self.cell65 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell65.setGeometry(QtCore.QRect(250, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell65.setFont(font)
        self.cell65.setObjectName("cell65")
        self.cell63 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell63.setGeometry(QtCore.QRect(130, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell63.setFont(font)
        self.cell63.setObjectName("cell63")
        self.cell66 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell66.setGeometry(QtCore.QRect(310, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell66.setFont(font)
        self.cell66.setObjectName("cell66")
        self.cell62 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell62.setGeometry(QtCore.QRect(70, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell62.setFont(font)
        self.cell62.setObjectName("cell62")
        self.cell69 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell69.setGeometry(QtCore.QRect(490, 350, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell69.setFont(font)
        self.cell69.setObjectName("cell69")
        self.cell54 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell54.setGeometry(QtCore.QRect(190, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell54.setFont(font)
        self.cell54.setObjectName("cell54")
        self.cell58 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell58.setGeometry(QtCore.QRect(430, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell58.setFont(font)
        self.cell58.setObjectName("cell58")
        self.cell57 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell57.setGeometry(QtCore.QRect(370, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell57.setFont(font)
        self.cell57.setObjectName("cell57")
        self.cell51 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell51.setGeometry(QtCore.QRect(10, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell51.setFont(font)
        self.cell51.setObjectName("cell51")
        self.cell55 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell55.setGeometry(QtCore.QRect(250, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell55.setFont(font)
        self.cell55.setObjectName("cell55")
        self.cell53 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell53.setGeometry(QtCore.QRect(130, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell53.setFont(font)
        self.cell53.setObjectName("cell53")
        self.cell56 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell56.setGeometry(QtCore.QRect(310, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell56.setFont(font)
        self.cell56.setObjectName("cell56")
        self.cell52 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell52.setGeometry(QtCore.QRect(70, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell52.setFont(font)
        self.cell52.setObjectName("cell52")
        self.cell59 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell59.setGeometry(QtCore.QRect(490, 290, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell59.setFont(font)
        self.cell59.setObjectName("cell59")
        self.cell44 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell44.setGeometry(QtCore.QRect(190, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell44.setFont(font)
        self.cell44.setObjectName("cell44")
        self.cell48 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell48.setGeometry(QtCore.QRect(430, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell48.setFont(font)
        self.cell48.setObjectName("cell48")
        self.cell47 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell47.setGeometry(QtCore.QRect(370, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell47.setFont(font)
        self.cell47.setObjectName("cell47")
        self.cell41 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell41.setGeometry(QtCore.QRect(10, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell41.setFont(font)
        self.cell41.setObjectName("cell41")
        self.cell45 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell45.setGeometry(QtCore.QRect(250, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell45.setFont(font)
        self.cell45.setObjectName("cell45")
        self.cell43 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell43.setGeometry(QtCore.QRect(130, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell43.setFont(font)
        self.cell43.setObjectName("cell43")
        self.cell46 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell46.setGeometry(QtCore.QRect(310, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell46.setFont(font)
        self.cell46.setObjectName("cell46")
        self.cell42 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell42.setGeometry(QtCore.QRect(70, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell42.setFont(font)
        self.cell42.setObjectName("cell42")
        self.cell49 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell49.setGeometry(QtCore.QRect(490, 230, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell49.setFont(font)
        self.cell49.setObjectName("cell49")
        self.cell34 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell34.setGeometry(QtCore.QRect(190, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell34.setFont(font)
        self.cell34.setObjectName("cell34")
        self.cell38 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell38.setGeometry(QtCore.QRect(430, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell38.setFont(font)
        self.cell38.setObjectName("cell38")
        self.cell37 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell37.setGeometry(QtCore.QRect(370, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell37.setFont(font)
        self.cell37.setObjectName("cell37")
        self.cell31 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell31.setGeometry(QtCore.QRect(10, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell31.setFont(font)
        self.cell31.setObjectName("cell31")
        self.cell35 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell35.setGeometry(QtCore.QRect(250, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell35.setFont(font)
        self.cell35.setObjectName("cell35")
        self.cell33 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell33.setGeometry(QtCore.QRect(130, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell33.setFont(font)
        self.cell33.setObjectName("cell33")
        self.cell36 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell36.setGeometry(QtCore.QRect(310, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell36.setFont(font)
        self.cell36.setObjectName("cell36")
        self.cell32 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell32.setGeometry(QtCore.QRect(70, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell32.setFont(font)
        self.cell32.setObjectName("cell32")
        self.cell39 = QtWidgets.QTextEdit(self.centralwidget)
        self.cell39.setGeometry(QtCore.QRect(490, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.cell39.setFont(font)
        self.cell39.setObjectName("cell39")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 9, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 50, 101, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 50, 101, 41))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuexit = QtWidgets.QMenu(self.menubar)
        self.menuexit.setObjectName("menuexit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuexit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cell11.setHtml(
            _translate(
                "MainWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"
            ))
        self.label.setText(_translate("MainWindow", "SUDOKU"))
        self.pushButton.setText(_translate("MainWindow", "SOLVE"))
        self.pushButton_2.setText(_translate("MainWindow", "GENERATE"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuexit.setTitle(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
